comptes/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (login,
                                       logout,
                                       password_reset,
                                       password_reset_done,
                                       password_reset_confirm,
                                       password_reset_complete,
                                       )
from .views import home, register, profile, edit, passe_change

urlpatterns = [
    url(r'^$', home, name="home"),
    url(r'^register/$', register, name="register"),
    url(r'^login/$', login, {'template_name': 'comptes/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'comptes/logout.html'}, name='logout'),
    url(r'^profile/$', profile, name="profile"),
    url(r'^profile/edit/$', edit, name="edit"),
    url(r'^passe_change/$', passe_change, name="passe_change"),
    url(r'^password-reset/$', password_reset, {'template_name': 'comptes/reset_password.html', 'post_reset_redirect':'comptes:password_reset_done', 'email_template_name':'comptes/reset_passe_email.html'}, name="password_reset"),
    url(r'^password-reset/done/$', password_reset_done, {'template_name': 'comptes/password_reset_done.html'}, name="password_reset_done"),
    url(r'^password-reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm,{'template_name': 'comptes/reset_password_confirm.html', 'post_reset_redirect':'comptes:password_reset_complete'},  name="password_reset_confirm"),
    url(r'^password-reset/complete/$',password_reset_complete,{'template_name': 'comptes/reset_password_complete.html'}, name="password_reset_complete"),
]

tutos/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .views import login_redirect

urlpatterns = [
    url(r'^$', login_redirect, name='login_redirect'),
    url(r'^admin/', admin.site.urls),
    url(r'^comptes/', include('comptes.urls', namespace='comptes', app_name='comptes'))
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comptes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete='CASCADE')
    description = models.CharField(max_length=120, default='')
    ville = models.CharField(max_length=120)
    site_web = models.URLField(blank=True)
    contacts = models.CharField(max_length=50)
    image = models.ImageField(upload_to='profile_image', blank=True)

    def __unicode__(self):
        return self.user.username

def nv_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])

post_save.connect(nv_profile, sender=User)


# Create your models here.

comptes/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class InscriptionForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = [
            'last_name',
            'first_name',
            'email',
            'username',
            'password1',
            'password2',
        ]

    def save(self, commit=True):
        user = super(InscriptionForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user

class EditProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            "last_name",
            "first_name",
            "email",
            "password",
        ]
        exclude = [

        ]

comptes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required


from .forms import InscriptionForm, EditProfileForm

def home(request):
    return render(request, 'comptes/home.html', {})

def login(request):
    return render(request, 'comptes/login.html', {})

def register(request):
    if request.method =='POST':
        form = InscriptionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('compte:home')
    else:
        form = InscriptionForm()
    context = {
        'form': form,
    }
    return render(request, 'comptes/register.html', context)

@login_required
def profile(request):
    context = {
        'user':request.user,
    }
    return render(request, 'comptes/profile.html', context)

@login_required
def edit(request):
    instance = request.user
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=instance)

        if form.is_valid():
            form.save()
            return redirect('comptes:profile')
    else:
        form = EditProfileForm(instance=instance)
    context = {
        'form':form,
        'instance':instance,
    }
    return render(request, 'comptes/edit.html', context)

@login_required
def passe_change(request):
    user = request.user
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('comptes:profile')
        else:
            return redirect('comptes:passe_change')
    else:
        form = PasswordChangeForm(user=user)
    context = {
        'form':form,
        'user':user,
    }
    return render(request, 'comptes/passe_change.html', context)







# Create your views here.

tutos/views.py
from django.shortcuts import redirect

def login_redirect(request):
    return redirect('/comptes/login')

comptes/templates/comptes/edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="text-center">
                    Formulaire de Modification
                </h4>
            </div>
            <div class="panel-body">
                <form method="post" action=".">{% csrf_token %}
                    <fieldset>
                        {% bootstrap_form form %}
                        <hr />
                        {% buttons %}
                            <p class="text-center">
                                <button type="submit" class="btn btn-primary">
                                {% bootstrap_icon "check" %} Enregistrer
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    {% bootstrap_icon "refresh" %}  Annuler
                                </button>
                            </p>
                        {% endbuttons %}
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

comptes/templates/comptes/home.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
    {% if user.is_authenticated %}
            <h1>Bienvenus {{ user.username }}</h1>
    {% endif %}
        <p class="lead">Quoi de neuf ??</p>
{% endblock %}

comptes/templates/comptes/login.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1 class="page-header">Bienvenus</h1>
    <p>
        Utiliser le Formulaire ci-dessous pour vous connecter
    </p>
    <div class="col-md-6 col-md-offset-3">
        <h2 class="page-header">Connexion</h2>
        <form method="POST" action=".">{% csrf_token %}
            <fieldset>
                {% bootstrap_form form %}
                <hr />
                {% buttons %}
                    <p class="text-center">
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "check" %} Connexion
                        </button>
                        <button type="reset" class="btn btn-danger">
                            {% bootstrap_icon "refresh" %}  Annuler
                        </button>
                    </p>
                {% endbuttons %}
            </fieldset>
        </form>
    </div>
{% endblock %}

comptes/templates/comptes/logout.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1 class="page-header">Déconnexion</h1>
    <p>
        Merci pour le temps que vous avez accordé à ce site aujourd'hui.
    </p>
{% endblock %}

comptes/templates/comptes/passe_change.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block content %}
    <div class="col-sm-8 col-sm-offset-2">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="text-center">
                    Formulaire de Modification
                </h4>
            </div>
            <div class="panel-body">
                <form method="post" action=".">{% csrf_token %}
                    <fieldset>
                        {% bootstrap_form form %}
                        {% buttons %}
                            <button type="submit" class="btn btn-primary">
                                {% bootstrap_icon "check" %} Modifier
                            </button>
                            <button type="reset" class="btn btn-danger">
                                {% bootstrap_icon "refresh" %}  Annuler
                            </button>
                        {% endbuttons %}
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

comptes/templates/comptes/password_reset_done.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="page-header text-center">
        Message de réinitialisation du mot de passe envoyé
    </h3>
    <div class="col-md-6 col-md-offset-3">
        <p class="text-lead text-center">
            Nous vous avons envoyé par courriel les instructions pour changer de mot de passe,
            pour autant qu'un compte existe avec l'adresse que vous avez indiquée. Vous devriez recevoir rapidement ce message.
            Si vous ne recevez pas de message, vérifiez que vous avez saisi l'adresse avec laquelle vous vous êtes enregistré et
            contrôlez votre dossier de pourriels.
        </p>

    </div>
{% endblock %}

comptes/templates/comptes/profile.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            {% if user.userprofile.image %}
                <img src="{{ user.userprofile.image.url }}" class="avatar img-circle img-thumbnail" alt="{{ user.userprofile.user }}"height="200" width="200">
            {% endif %}
        </div>
        <div class="col-md-8">
            <p>
                <p>Utilisateur : {{ user }}</p>
                <p>Nom : {{ user.last_name }}</p>
                <p>Prénoms : {{ user.first_name }}</p>
                <p>Courriel : {{ user.email }}</p>
            </p>
            <p>Description : {{ user.userprofile.description }}</p>
            <p>Contacts : {{ user.userprofile.contacts }}</p>
            <p>Résident à : {{ user.userprofile.ville }}</p>
            <p>Site Web : <a href="{{ user.userprofile.site_web }}">{{ user.userprofile.site_web }}</a></p>
        </div>
    </div>
{% endblock %}

comptes/templates/comptes/register.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h1 class="page-header">Inscription</h1>
    <div class="col-md-6 col-md-offset-3">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4 class="text-center">
                    Formulaire d'Inscription
                </h4>
            </div>
            <div class="panel-body">
                <form method="POST" action=".">{% csrf_token %}
                    <fieldset>
                        {% bootstrap_form form %}
                        <hr />
                        {% buttons %}
                            <p class="text-center">
                                <button type="submit" class="btn btn-primary">
                                    {% bootstrap_icon "check" %} Inscription
                                </button>
                                <button type="reset" class="btn btn-danger">
                                    {% bootstrap_icon "refresh" %}  Annuler
                                </button>
                            </p>
                        {% endbuttons %}
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

comptes/templates/comptes/reset_passe_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'comptes:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}

comptes/templates/comptes/reset_password.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="page-header text-center">
        Mot de passe perdu ?
        Saisissez votre adresse électronique ci-dessous et nous vous enverrons
        les instructions pour en créer un nouveau.
    </h3>
    <div class="col-md-6 col-md-offset-3">
        <h2 class="page-header">Réinitialiser Mon Mot de Passe</h2>
        <form method="POST" action=".">{% csrf_token %}
            <fieldset>
                {% bootstrap_form form %}
                <hr />
                {% buttons %}
                    <p class="text-center">
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "refresh" %} Réinitialiser mon Mot de Passe
                        </button>
                    </p>
                {% endbuttons %}
            </fieldset>
        </form>
    </div>
{% endblock %}

comptes/templates/comptes/reset_password_complete.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="page-header text-center">
        Mot de Passe réinitialiser avec Success
    </h3>
    <div class="col-md-6 col-md-offset-3">
        <p class="text-lead text-center">
            Félicitation votre Mot de passe a été réinitialiser avec Success !!
        </p>
        <p class="text-center">
            <a href="{% url 'comptes:login' %}">Retour à la page de Connexion</a>
        </p>


    </div>
{% endblock %}

comptes/templates/comptes/reset_password_confirm.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <h3 class="page-header text-center">
        Saisissez deux fois votre nouveau mot de passe afin de vérifier qu'il est correctement saisi.
    </h3>
    <div class="col-md-6 col-md-offset-3">
        <h2 class="page-header">Saisissez un nouveau mot de passe</h2>
        <form method="POST" action=".">{% csrf_token %}
            <fieldset>
                {% bootstrap_form form %}
                <hr />
                {% buttons %}
                    <p class="text-center">
                        <button type="submit" class="btn btn-primary">
                            {% bootstrap_icon "edit" %} Modifier mon Mot de Passe
                        </button>
                    </p>
                {% endbuttons %}
            </fieldset>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link href="//fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/6.0.0/normalize.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
    <div class="container">
    <br/>
    {% include 'navbar.html' %}
        {% block content %}
        {% endblock %}
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Friendship</a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
      {% if user.is_authenticated %}
        <ul class="nav navbar-nav">
            <li><a href="{% url 'comptes:home' %}">Acceuil</a></li>
            <li><a href="{% url 'comptes:profile' %}">Profile</a></li>
            <li><a href="{% url 'comptes:edit' %}">Modifier Profile</a></li>
            <li><a href="{% url 'comptes:passe_change' %}">Change Passe</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'comptes:logout' %}">Déconnexion</a></li>
        </ul>
      {% else %}
        <ul class="nav navbar-nav">
            <li><a href="{% url 'comptes:password_reset' %}">Réinitialiser Passe</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'comptes:login' %}">Connexion</a></li>
            <li><a href="{% url 'comptes:register' %}">Inscription</a></li>
        </ul>
      {% endif %}
      </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
  </nav>